# Page settings

baseURL = "http://example.org/"
languageCode = "en"
title = ""
theme = "hugo-devresume-theme"
googleAnalytics = "UA-XXXXXXX-Y"






[params]
    author = "CowboySmall"
    description = "DevResume - Bootstrap 4 Resume/CV Template For Software Developers"


    primaryColor = "#b65494"
    textPrimaryColor = "#191919"


    [params.profile]
        enable = true
        name = "Zouabi Arwa"
        tagline = "Technicien superieur en reseaux et telecommunication"
        avatar = "arwa.jpg"







    [params.contact]
        enable = true
        location = "Tunisia"

        [[params.contact.list]]
        icon = "fas fa-phone-square"
        url = "tel:#"
        text = "21624455760"
        [[params.contact.list]]
        icon = "fas fa-envelope-square"
        url = "mailto:#"
        text = "zouebiiaroua11@gmail.com"

    [params.skills]
        enable = true

        [[params.skills.list]]
        title = "Qualification et competence"
        [[params.skills.list.items]]
        details = "Installation et maintenance de la connectique et des       equipements"
        [[params.skills.list.items]]
        details = "Configuration des reseaux"
        [[params.skills.list.items]]
        details = "Maintennance de reseaux supportant la configuration CISCO"
        [[params.skills.list.items]]
        details = "Rétablit le service en cas de problèmes ou de pannes réseau"
        [[params.skills.list.items]]
        details = "Assure un suivi technique auprès des utilisateurs"




      [params.education]
        enable = true
       
        [[params.education.list]]
        degree = "diplome technicien Superieur en reseaux et telecommunication"
        university = "Faculte de science de bizerte"
        dates = "2012 - 2015"
        [[params.education.list]]
        degree = "diplome mastere en securite informatique et infrastructure"
        university = "Institut Superieur de l'informatique-ISI"
        dates = "2019 - 2021"





        
       
   [params.languages]
        enable = true


        [[params.languages.list]]
        name = "Arabe"
        level = "Native"
        [[params.languages.list]]
        name = "Francais"
        level = "Professional"
        [[params.languages.list]]
        name = "Anglais"
        level = "Professional"
        
      




    [params.summary]
        enable = true
        text = "Technicien qualifie avec experience dans le domaine de la telecommunication et des reseaux avec ou sans fil. Expert en installation et en maintenance des equipements de telecommunication, des materiels informatiques et des logiciels. Maitrise les techniques de reparation et de consultation des systemes analogiques et numeriques."

    [params.experience]
        enable = true

        [[params.experience.list]]
        title = "techncien superieur en reseaux informatique"
        dates = "2017 - 2020"
        company = "Archidoc-SA"
        details = "installer les equipements (routeurs, commutateurs, multiplexeurs, cables, systemes d’extinction d’incendies,Installer les connexions et les outils d’acces a distance,Detecter et depanner les eventuelles anomalies."

        [[params.experience.list]]
        title = "STAGE DE FIN D’ÉTUDE"
        dates = "Fevrier - juin 2015"
        company = "Société Tunisie Télécom "
        details = "Réaliser un système de gestion électronique des documents."

        [[params.experience.list]]
        title = "STAGE D'ETE"
        dates = "juillet2014- aout2014"
        company = "Steg"
        details = "Installer des reseaux suivant la commande de la clientele, les caracteristiques techniques et les manuels,Concevoir et organiser des diagrammes pour l’etablissement de sites."
        
         [[params.experience.list]]
        title = "STAGE D'ETE"
        dates = "juin 2014 - juillet 2014"
        company = "TUNISIE TELCOM"
        details = "Installation et maintenance de la connectique et des equipements,Évaluer l’installation de sites afin de determiner les outils et equipements necessaires,Commander les materiels et les fournitures selon le besoin des projets.."

 
        
[params.interests]
 enable = true

        [[params.interests.list]]
        name = "Climbing"
        [[params.interests.list]]
        name = "Snowboarding"
        [[params.interests.list]]
        name = "Photography"
        [[params.interests.list]]
        name = "Travelling"



        [params.social]
        enable = true

        [[params.social.list]]
        icon = "fab fa-github-square"
        url = "//github.com/username"
        title = "username"
        [[params.social.list]]
        icon = "fab fa-linkedin"
        url = "//linkedin.com/in/username"
        title = "username"
        [[params.social.list]]
        icon = "fab fa-twitter-square"
        url = "//twitter.com/username"
        title = "@username"





